namespace: agri
image:
  # GitHub Actions updates this field after each build.
  registry: ghcr.io/qudrat111/agri_culture_project
  tag: "9c0c242024c4faf77921d728f9049ab77d370d07"
services:
  order:
    replicas: 1
  saga:
    replicas: 1
  inventory:
    replicas: 1
  query:
    replicas: 1
    serviceType: LoadBalancer
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi
prometheus:
  scrape: true
  path: /actuator/prometheus
