namespace: agri
image:
  # GitHub Actions updates this field after each build.
  registry: ghcr.io/qudrat111/agri_culture_project
  tag: "ed466458621aea8841dbd2c83baa40e5c4707a0d"
services:
  order:
    replicas: 1
  saga:
    replicas: 1
  inventory:
    replicas: 1
  query:
    replicas: 1
    serviceType: LoadBalancer
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi
prometheus:
  scrape: true
  path: /actuator/prometheus
