namespace: agri
image:
  # GitHub Actions updates this field after each build.
  registry: ghcr.io/qudrat111/agri_culture_project
  tag: "d9745fe7f219f50dd069b5eb5fe7c3c9b3b8c035"
services:
  order:
    replicas: 1
  saga:
    replicas: 1
  inventory:
    replicas: 1
  query:
    replicas: 1
    serviceType: LoadBalancer
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi
prometheus:
  scrape: true
  path: /actuator/prometheus
