namespace: agri
image:
  # GitHub Actions updates this field after each build.
  registry: ghcr.io/qudrat111/agri_culture_project
  tag: "245fa7ae0dc2002879b013dae558872a8b5b097b"
services:
  order:
    replicas: 1
  saga:
    replicas: 1
  inventory:
    replicas: 1
  query:
    replicas: 1
    serviceType: LoadBalancer
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 750m
    memory: 1Gi
prometheus:
  scrape: true
  path: /actuator/prometheus
